name: speechenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - setuptools
  - nvidia/label/cuda-12.2.2::cuda-toolkit
  - pip
  - pip:
    - matplotlib==3.6.0
    - numpy==1.20.1
    - scipy==1.6.2
    - torch==2.2.0
    - torchvision==0.17.0
    - visdom==0.2.4